# -*- coding: utf-8 -*-
"""TF2.0 Tensors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-oHPC3ynl_iIbcJBGnXmdo_agp_q3zyN
"""

#Import tensorflow
import tensorflow as tf
print(tf.__version__)

# prompt: Generate a 2*2 tensor

two_d_tensor = tf.constant([[1,2],[3,4]])
two_d_tensor

three_d_tensor = tf.expand_dims(two_d_tensor, axis=0)
three_d_tensor

three_d_tensor = tf.expand_dims(two_d_tensor, axis=1)
three_d_tensor

three_d_tensor = tf.expand_dims(two_d_tensor, axis=-1)
three_d_tensor

two_d_tensor[0]

two_d_tensor[:, 1]

two_d_tensor[:, :]